spring:
    jpa: 
      generate-ddl: true
    
      hibernate:
        ddl-auto: update
    
      properties:
        hibernate:
          default_batch_fetch_size: 1000
          
    output:
        ansi:
            enabled: always # make colorful
    datasource:
        url: jdbc:h2:tcp://localhost/~/seoul/db    
        username: sa
        password: 
        driver-class-name: org.h2.Driver


    
      